
const books = module.exports =
[
  { "id": 1, "title": "The Silent Forest", "author": "Amit Verma" },
  { "id": 2, "title": "Beyond the Horizon", "author": "Neha Sharma" },
  { "id": 3, "title": "Code of Destiny", "author": "Rahul Mehta" },
  { "id": 4, "title": "Whispers of Time", "author": "Anjali Rao" },
  { "id": 5, "title": "The Last Algorithm", "author": "Suresh Patel" },
  { "id": 6, "title": "Journey to Nowhere", "author": "Kavita Iyer" },
  { "id": 7, "title": "Debugging Life", "author": "Arjun Malhotra" },
  { "id": 8, "title": "Parallel Worlds", "author": "Ritu Saxena" },
  { "id": 9, "title": "Infinite Loops", "author": "Vikram Singh" },
  { "id": 10, "title": "The Lost Variable", "author": "Pooja Nair" },

  { "id": 11, "title": "Echoes of Memory", "author": "Manish Gupta" },
  { "id": 12, "title": "Binary Dreams", "author": "Sneha Kulkarni" },
  { "id": 13, "title": "Lines of Fate", "author": "Rohan Desai" },
  { "id": 14, "title": "The Forgotten Path", "author": "Priya Kapoor" },
  { "id": 15, "title": "Logic & Lies", "author": "Kunal Bansal" },
  { "id": 16, "title": "Shadows in Code", "author": "Meenal Joshi" },
  { "id": 17, "title": "Fragments of Tomorrow", "author": "Aditya Khanna" },
  { "id": 18, "title": "Runtime Errors", "author": "Nisha Arora" },
  { "id": 19, "title": "The Final Commit", "author": "Siddharth Jain" },
  { "id": 20, "title": "Patterns of Truth", "author": "Ishita Goyal" },

  { "id": 21, "title": "Beyond the Stack", "author": "Ankit Tiwari" },
  { "id": 22, "title": "Silent Exceptions", "author": "Tanvi Chaturvedi" },
  { "id": 23, "title": "Recursive Souls", "author": "Mohit Agarwal" },
  { "id": 24, "title": "Threads of Reality", "author": "Shalini Mishra" },
  { "id": 25, "title": "The Hidden Node", "author": "Deepak Yadav" },
  { "id": 26, "title": "Encrypted Hearts", "author": "Ayesha Khan" },
  { "id": 27, "title": "Chronicles of Logic", "author": "Harsh Vardhan" },
  { "id": 28, "title": "The Broken Build", "author": "Simran Kaur" },
  { "id": 29, "title": "Signals & Signs", "author": "Nitin Chawla" },
  { "id": 30, "title": "The Final Output", "author": "Rashmi Shetty" },

  { "id": 31, "title": "Unknown Dependencies", "author": "Aakash Mishra" },
  { "id": 32, "title": "Flow of Control", "author": "Bhavya Jain" },
  { "id": 33, "title": "Between the Brackets", "author": "Yash Agarwal" },
  { "id": 34, "title": "Hidden Bugs", "author": "Komal Shah" },
  { "id": 35, "title": "The Last Test Case", "author": "Naveen Kumar" },
  { "id": 36, "title": "Version Unknown", "author": "Pallavi Deshpande" },
  { "id": 37, "title": "Syntax of Life", "author": "Ritesh Pandey" },
  { "id": 38, "title": "Through the Compiler", "author": "Apoorva Sen" },
  { "id": 39, "title": "The Missing Semicolon", "author": "Devansh Srivastava" },
  { "id": 40, "title": "Designing Tomorrow", "author": "Swati Malhotra" },

  { "id": 41, "title": "Inside the Loop", "author": "Sanjay Verma" },
  { "id": 42, "title": "Beyond the Framework", "author": "Ira Banerjee" },
  { "id": 43, "title": "Breaking the Pattern", "author": "Abhishek Roy" },
  { "id": 44, "title": "Silent Servers", "author": "Rachit Goel" },
  { "id": 45, "title": "The Infinite Queue", "author": "Namrata Kulkarni" },
  { "id": 46, "title": "Lost in Production", "author": "Parth Shah" },
  { "id": 47, "title": "Code & Consequences", "author": "Shubham Mishra" },
  { "id": 48, "title": "System Design Diaries", "author": "Neelam Arvind" },
  { "id": 49, "title": "The Last Deployment", "author": "Kartik Bhat" },
  { "id": 50, "title": "Scalable Dreams", "author": "Aarohi Mehta" }
]
